name: CI for xy_bits Program

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # Step 2: Set up Docker container with Ubuntu 16.04 (32-bit)
      - name: Set up Docker container with Ubuntu 16.04
        run: |
          docker pull i386/ubuntu:16.04

      # Step 3: Run build and tests inside the 32-bit Docker container
      - name: Build and run tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace i386/ubuntu:16.04 /bin/bash -c "
            apt-get update &&
            apt-get install -y gcc make diffutils git &&
            cd Mmn_11/xy_bits &&
            # Build the xy_bits executable
            make all &&
            # Run the tests and generate output
            make run-tests
            "

      # Step 4: Commit and push the test results and the new executable
      - name: Commit and push output files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are any changes to commit
          if git status --porcelain | grep -q '^'; then
            git add Mmn_11/xy_bits/exe/xy_bits Mmn_11/xy_bits/tests/output/test*
            git commit -m "Updated xy_bits executable and test output files"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit"
          fi